- name: AWX execution context test
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Show current working directory
      command: pwd
      register: pwd_out

    - name: List project root
      command: ls -la
      register: ls_out

    - name: FORCE DEBUG OUTPUT
      debug:
        var: pwd_out

    - name: FORCE DEBUG LS
      debug:
        var: ls_out.stdout_lines
