- name: AWX execution context test
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Show current working directory
      command: pwd
      register: pwd_out

    - name: List project root
      command: ls -la
      register: ls_out

    - name: DEBUG | Print execution context
      debug:
        msg:
          - "PWD = {{ pwd_out.stdout }}"
          - "PROJECT FILES:"
          - "{{ ls_out.stdout_lines }}"
