- name: Test include_vars
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Load vars explicitly
      ansible.builtin.include_vars:
        file: vars/test_vars.yml

    - name: Debug vars
      debug:
        msg:
          - "message={{ test_message }}"
          - "number={{ test_number }}"
